image: debian:12-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_gcc:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install cmake g++ pkg-config
    - apt-get -y install freeglut3-dev libarchive-dev libjpeg62-turbo-dev libpng-dev libunshield-dev libxml2-dev libzip-dev zlib1g-dev
    - apt-get -y install unzip wget
    - export CC=gcc && export CXX=g++
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../ -DLONG_HASH_TESTS=OFF
    - make -j4
    - ctest -V

build_clang:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install cmake clang pkg-config
    - apt-get -y install freeglut3-dev libarchive-dev libjpeg62-turbo-dev libpng-dev libunshield-dev libxml2-dev libzip-dev zlib1g-dev
    - apt-get -y install unzip wget
    - export CC=clang && export CXX=clang++
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../ -DLONG_HASH_TESTS=OFF
    - make -j4
    - ctest -V
